version: '3.7'
services:
  php:
    working_dir: /app
    image: php:7.4.7
    volumes:
      - './:/app'
      - './sources/:/sources/:z'
      - './formatted/:/formatted/:z'
      - './examples/:/examples/:z'
    command:
      - 'php'
  composer:
    working_dir: /app
    image: composer
    command: install --ignore-platform-reqs
#    depends_on:
#      - php
    volumes:
      - './:/app'
      - './vendor/:/vendor/:z'
